from .discrete_connection_type import DiscreteConnectionTypeEmbeddingAttentionBias
from .discrete_connection_type_and_connection_rep import DiscreteConnectionTypeEmbeddingPlusConnectionRepresentationAttentionBias
from .base import AttentionBiasBase
