model = dict(
    type='Regressor',
    args=dict(
        num_layers=0,
        input_dim=1024,
        output_dim=1,
        model_config=dict(
            type='GraphRelativePositionalEncodingNetworkAdvanced',
            args=dict(
                model_dimension=1024,
                number_of_heads=32,
                number_of_layers=18,
                feedforward_dimension=1024,
                dropout=0.1,
                attention_dropout=0.1,
                shortest_path_length_upperbound=5,
                perturbation=0.0,
                independent_layer_embeddings=False,
                attention_biases=[
                    'edge',
                    'shortest_path_length',
                    # 'shortest_path'
                ],
                path_encoding_length_upperbound=5,
                path_encoding_code_dim=4,
                encode_node_degree_centrality=True
            )
        )
    )
)
