from .supervised import Regressor, RegressorWithKPGTRegularization, RegressorWithKPGTFusion, RegressorWithKPGTAttentionFusion
from .self_supervised import SingleModelMultiViewPretrainingWithPretexts, SingleModelSingleViewPretrainingWithPretexts
