from .supervised import Regressor, RegressorWithKPGTRegularization, RegressorWithKPGTFusion
from .self_supervised import SingleModelMultiViewPretrainingWithPretexts, SingleModelSingleViewPretrainingWithPretexts
