model = dict(
    type='Regressor',
    args=dict(
        num_layers=0,
        input_dim=256,
        output_dim=1,
        model_config=dict(
            type='CoAtGINGeneralPipeline',
            args=dict(
                node_encoder_config=dict(
                    type='GNNWithVirtualNode',
                    args=dict(
                        num_layers=4,
                        model_dim=256,
                        drop_ratio=0.,
                        JK="last",
                        residual=False,
                        gnn_type='gcn',
                        line_graph=False,
                        pos_features=None
                    )
                ),
                graph_pooling="sum"
            )
        )
    )
)
